// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVzxxx',
    appId: '1:xxx:web:xxx',
    messagingSenderId: 'xxx',
    projectId: 'accident-report-xxx',
    authDomain: 'accident-report-xxx.firebaseapp.com',
    storageBucket: 'accident-report-xxx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVzxxx',
    appId: '1:xxx:android:xxx',
    messagingSenderId: 'xxx',
    projectId: 'accident-report-xxx',
    storageBucket: 'accident-report-xxx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVVzxxx',
    appId: '1:xxx:ios:xxx',
    messagingSenderId: 'xxx',
    projectId: 'accident-report-xxx',
    storageBucket: 'accident-report-xxx.appspot.com',
    iosBundleId: 'com.realtime.report',
  );
}
